Use shellcheck to fix warnings

diff --git a/run_all b/run_all
--- a/run_all
+++ b/run_all
@@ -13,7 +13,7 @@ if [ "$1" = "-h" ]; then
   echo "   FOLDER=dev MINDEPTH=2 run_all ls -l"
   echo "   FILTER=oss run_all ls -l"
   echo "   FILTER=asdf|zsh run_all git fo"
-  exit -1
+  exit 1
 fi
 
 pushd() {
@@ -21,12 +21,13 @@ pushd() {
 }
 
 popd() {
-  command popd "$@" > /dev/null
+  command popd > /dev/null
 }
 
 MINDEPTH=${MINDEPTH:-1}
 MAXDEPTH=${MAXDEPTH:-3}
 FOLDER=${FOLDER:-.}
+FILTER=${FILTER:-}
 
 date
 
@@ -37,33 +38,33 @@ if [ "$FILTER" != "" ]; then
 fi
 tput sgr0 2>/dev/null # go back to normal text
 
-DIRECTORIES=`GREP_OPTIONS= ; find $FOLDER -mindepth $MINDEPTH -maxdepth $MAXDEPTH -name ".git" -type d 2>/dev/null | egrep -i "$FILTER" | sed "s/\.\///" | sed "s/\/\.git//" | sort`
+# shellcheck disable=SC2034
+DIRECTORIES=$(GREP_OPTIONS= ; find "$FOLDER" -mindepth "$MINDEPTH" -maxdepth "$MAXDEPTH" -name ".git" -type d 2>/dev/null | grep -iE "$FILTER" | sed "s/\.\///" | sed "s/\/\.git//" | sort)
 
 if [[ "$FOLDER" == "." ]] && [[ "$PWD" == "$HOME" ]] || [[ "$FOLDER" == "$HOME" ]]; then
-  # Note: This line will also remove '.git' from the current folder if the current folder is itself a git repo
-  # Note: Leave the trailing space for matching in here
-  DIRECTORIES=`echo $DIRECTORIES | sed "s|$HOME\ | |" | sed "s|$HOME\/\ | |" | sed "s/\.git//"`
-
+  # Note: Leave the trailing space for matching in here; Also, do not double-quote since it fails to remove the $HOME folder
+  # shellcheck disable=SC2086
+  DIRECTORIES=$(echo $DIRECTORIES | sed "s|$HOME\ ||" | sed "s|$HOME\/\ ||")
   # Note: This line will remove my repo in '~/Library' folder
-  DIRECTORIES=`echo $DIRECTORIES | sed "s|$HOME\/Library||" | sed "s|Library||"`
+  DIRECTORIES=$(echo "$DIRECTORIES" | sed "s|$HOME\/Library||" | sed "s|Library||")
   # Note: This line will remove my repo in '~/.vscode' folder
-  DIRECTORIES=`echo $DIRECTORIES | sed "s|$HOME\/\.vscode||" | sed "s|.vscode||"`
+  DIRECTORIES=$(echo "$DIRECTORIES" | sed "s|$HOME\/\.vscode||" | sed "s|.vscode||")
   # Note: This line will remove my repo in '~/tmp' folder
-  DIRECTORIES=`echo $DIRECTORIES | sed "s|$HOME\/tmp||" | sed "s|tmp||"`
+  DIRECTORIES=$(echo "$DIRECTORIES" | sed "s|$HOME\/tmp||" | sed "s|tmp||")
 fi
 
-TOTAL_COUNT=`echo $DIRECTORIES | wc -w`
+TOTAL_COUNT=$(echo "$DIRECTORIES" | wc -w)
 
 COUNT=1
 for dir in $DIRECTORIES; do
-  if [ -d $dir -a ! -h $dir ]; then
+  if [ -d "$dir" ] && [ ! -h "$dir" ]; then
     tput setaf 2 2>/dev/null  # bright green text
-    echo ">>>>>>>>>>>>>>>>>>>>> [$COUNT of $TOTAL_COUNT] "$*" (in $dir) <<<<<<<<<<<<<<<<<<<<"
+    echo ">>>>>>>>>>>>>>>>>>>>> [$COUNT of $TOTAL_COUNT] '$*' (in '$dir') <<<<<<<<<<<<<<<<<<<<"
     tput sgr0 2>/dev/null # go back to normal text
-    pushd $dir
+    pushd "$dir" || return
     bash -c "$*"
-    popd
-    let COUNT=COUNT+1
+    popd || return
+    (( COUNT++ )) || true
   fi
 done
 
